logo: # add logo name
title: Voyage 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4
banner-title: Voyage
banner-desc: 

# Author settings
author-pic: amit.jpg 
author-name: Amit Singh
about-author: Developer
email: amit2020cs@gmail.com
phone: 8630684627 
website: https://amit2020cs@github.io

# Social link
google_url:    https://plus.google.com/u/1/106448500629945231088
twitter_url:   https://twitter.com/amit2020rocks
instagram_url: https://www.instagram.com/amit2020cs/
pinterest_url: https://in.pinterest.com/amit2020cs/
facebook_url:  https://www.facebook.com/Amit2020rocks

# Disqus
discus_identifier: # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
# Paginate: 12
paginate_path: /page:num/



# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
